#!/bin/sh
export DBUS_SESSION_BUS_ADDRESS='unix:path=/run/user/1000/bus' # for notify-send

file=`python3 -c "$(printf 'import sys, urllib.parse\nprint(urllib.parse.unquote(sys.argv[1]))')" $3`
# pdffonts $file | grep -q 'Type 1C' && { notify-send 'Printing failed' 'Type 1'; exit; }

( printf '\e%%-12345X'
  echo @PJL JOB
  if ! echo $5 | grep -q Duplex=None; then
    echo @PJL SET DUPLEX=ON
  fi
  echo @PJL ENTER LANGUAGE=POSTSCRIPT
  cat $file
  printf '\e%%-12345X'
  echo @PJL EOJ
  printf '\e%%-12345X'
) | send-to-printer
if [ $? = 10 ]; then
  notify-send 'Printing failed' 'Printer is not powered on.'
fi
