#!/bin/sh
file=`python3 -c "$(printf 'import sys, urllib.parse\nprint(urllib.parse.unquote(sys.argv[1]))')" $3`
pdffonts $file | grep -q 'Type 1C' && { echo 'Type 1' | my-notify; exit; }

( printf '\e%%-12345X'
  echo @PJL JOB
  if ! echo $5 | grep -q Duplex=None; then
    echo @PJL SET DUPLEX=ON
  fi
  echo @PJL ENTER LANGUAGE=POSTSCRIPT
  cat $file
  printf '\e%%-12345X'
  echo @PJL EOJ
  printf '\e%%-12345X'
) | send-to-printer | my-notify
