#!/bin/sh

# This script is especially useful for fixing cweave pattern matching.

# compare two pdf files (by analogy with git diff)
#
#   git add -f file.pdf
#   <generate new variant of pdf file>
#   dvidiff file
#

if [ $1 = -n ]; then
  file=$2
else
  file=$1
fi

old=$file-oLd
new=$file-nEw

cp $file.pdf $new.pdf || exit
git checkout -q $file.pdf || exit
cp $file.pdf $old.pdf || exit
cp $new.pdf $file.pdf || exit

if [ `pdfinfo $old.pdf | sed -n 's/Pages:\s\+//p'` != `pdfinfo $new.pdf | sed -n 's/Pages:\s\+//p'` ]; then
  echo Number of pages in files is not equal
  exit 1
fi
old_hash=`dvihash $old`
new_hash=`dvihash $new`
pages=`diff $old_hash/hash $new_hash/hash | grep \< | cut -d' ' -f2`
pages=`printf '%d,' $pages | sed 's/,$//'`
[ "$pages" = 0 ] && exit
qpdf --pages . $pages -- $old.pdf --replace-input
qpdf --pages . $pages -- $new.pdf --replace-input
if [ $1 = -n ]; then
  echo $pages
else
  dvi $old
  dvi $new
fi
rm -r $old_hash $new_hash
exit 1
#TODO: remove 'rm ???' from dvihash
