#!/bin/sh
[ "$engine" = metapost ] && exit
if printenv lastpagenumber >/dev/null; then
  pages=`seq -s, $((lastpagenumber+1)) $total`','`seq -s, 1 $lastpagenumber`
  if printenv p >/dev/null; then
    pages=`printf '%s\n%s\n' $pages $p | dvipdfmx-select.pl`
  fi
  pages=`echo $pages | dvipdfmx-compress.pl`
else
  if printenv p >/dev/null; then
    pages=$p 
  else
    pages=-
  fi
fi
/bin/dvipdfmx -s $pages "$@"
ret=$?
eval rm \${$#}
exit $ret
