#!/bin/sh
[ "$engine" = metapost ] && exit
if printenv lastpagenumber >/dev/null; then
  if printenv p >/dev/null; then
    pages=`seq -s, $((lastpagenumber+1)) $total`','`seq -s, 1 $lastpagenumber`
    pages=`echo $pages | dvipdfmx-select.pl $p`
    pages=`echo $pages | dvipdfmx-compress.pl`
  else
    pages=$((lastpagenumber+1))-,-$lastpagenumber
  fi
else
  if printenv p >/dev/null; then
    pages=$p 
  else
    pages=-
  fi
fi
/bin/dvipdfmx -s $pages "$@"
ret=$?
eval rm \${$#}
exit $ret
