#!/bin/sh
[ "$engine" = metapost ] && exit
eval last=\${$#}
npages=`qpdf --show-npages ${last%.dvi}.pdf`
if printenv lastpagenumber >/dev/null; then
  pages=`seq -s, $((lastpagenumber+1)) $npages`','`seq -s, 1 $lastpagenumber`
else
  pages=`seq -s, 1 $npages`
fi
if printenv p >/dev/null; then
  true # TODO: reorder $pages according to $p
fi
# TODO: compress to ranges
/bin/dvipdfmx -s $pages "$@"
ret=$?
rm $last
exit $ret
