g++ -DHAVE_CONFIG_H -I.   -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++0x  -D_PPD_DEPRECATED=""    -g -O2 -ffile-prefix-map=/home/user/cups-filters-1.28.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wall  -D_GNU_SOURCE -c -o filter/pdftopdf/pdftopdf-pdftopdf.o `test -f 'filter/pdftopdf/pdftopdf.cc' || echo './'`filter/pdftopdf/pdftopdf.cc
g++ -DHAVE_CONFIG_H -I.   -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++0x  -D_PPD_DEPRECATED=""    -g -O2 -ffile-prefix-map=/home/user/cups-filters-1.28.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wall  -D_GNU_SOURCE -c -o filter/pdftopdf/pdftopdf-pdftopdf_jcl.o `test -f 'filter/pdftopdf/pdftopdf_jcl.cc' || echo './'`filter/pdftopdf/pdftopdf_jcl.cc
g++ -DHAVE_CONFIG_H -I.   -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++0x  -D_PPD_DEPRECATED=""    -g -O2 -ffile-prefix-map=/home/user/cups-filters-1.28.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wall  -D_GNU_SOURCE -c -o filter/pdftopdf/pdftopdf-pdftopdf_processor.o `test -f 'filter/pdftopdf/pdftopdf_processor.cc' || echo './'`filter/pdftopdf/pdftopdf_processor.cc
g++ -DHAVE_CONFIG_H -I.   -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++0x  -D_PPD_DEPRECATED=""    -g -O2 -ffile-prefix-map=/home/user/cups-filters-1.28.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wall  -D_GNU_SOURCE -c -o filter/pdftopdf/pdftopdf-qpdf_pdftopdf_processor.o `test -f 'filter/pdftopdf/qpdf_pdftopdf_processor.cc' || echo './'`filter/pdftopdf/qpdf_pdftopdf_processor.cc
g++ -DHAVE_CONFIG_H -I.   -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++0x  -D_PPD_DEPRECATED=""    -g -O2 -ffile-prefix-map=/home/user/cups-filters-1.28.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wall  -D_GNU_SOURCE -c -o filter/pdftopdf/pdftopdf-pptypes.o `test -f 'filter/pdftopdf/pptypes.cc' || echo './'`filter/pdftopdf/pptypes.cc
g++ -DHAVE_CONFIG_H -I.   -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++0x  -D_PPD_DEPRECATED=""    -g -O2 -ffile-prefix-map=/home/user/cups-filters-1.28.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wall  -D_GNU_SOURCE -c -o filter/pdftopdf/pdftopdf-nup.o `test -f 'filter/pdftopdf/nup.cc' || echo './'`filter/pdftopdf/nup.cc
g++ -DHAVE_CONFIG_H -I.   -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++0x  -D_PPD_DEPRECATED=""    -g -O2 -ffile-prefix-map=/home/user/cups-filters-1.28.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wall  -D_GNU_SOURCE -c -o filter/pdftopdf/pdftopdf-intervalset.o `test -f 'filter/pdftopdf/intervalset.cc' || echo './'`filter/pdftopdf/intervalset.cc
g++ -DHAVE_CONFIG_H -I.   -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++0x  -D_PPD_DEPRECATED=""    -g -O2 -ffile-prefix-map=/home/user/cups-filters-1.28.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wall  -D_GNU_SOURCE -c -o filter/pdftopdf/pdftopdf-qpdf_tools.o `test -f 'filter/pdftopdf/qpdf_tools.cc' || echo './'`filter/pdftopdf/qpdf_tools.cc
g++ -DHAVE_CONFIG_H -I.   -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++0x  -D_PPD_DEPRECATED=""    -g -O2 -ffile-prefix-map=/home/user/cups-filters-1.28.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wall  -D_GNU_SOURCE -c -o filter/pdftopdf/pdftopdf-qpdf_xobject.o `test -f 'filter/pdftopdf/qpdf_xobject.cc' || echo './'`filter/pdftopdf/qpdf_xobject.cc
g++ -DHAVE_CONFIG_H -I.   -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++0x  -D_PPD_DEPRECATED=""    -g -O2 -ffile-prefix-map=/home/user/cups-filters-1.28.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wall  -D_GNU_SOURCE -c -o filter/pdftopdf/pdftopdf-qpdf_pdftopdf.o `test -f 'filter/pdftopdf/qpdf_pdftopdf.cc' || echo './'`filter/pdftopdf/qpdf_pdftopdf.cc
g++ -DHAVE_CONFIG_H -I.   -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++0x  -D_PPD_DEPRECATED=""    -g -O2 -ffile-prefix-map=/home/user/cups-filters-1.28.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wall  -D_GNU_SOURCE -c -o filter/pdftopdf/pdftopdf-qpdf_cm.o `test -f 'filter/pdftopdf/qpdf_cm.cc' || echo './'`filter/pdftopdf/qpdf_cm.cc
g++ -std=c++0x  -D_PPD_DEPRECATED=""    -g -O2 -ffile-prefix-map=/home/user/cups-filters-1.28.6=. -fstack-protector-strong -Wformat -Werror=format-security -Wall  -D_GNU_SOURCE  -Wl,-z,relro -Wl,-z,now -o pdftopdf/pdftopdf filter/pdftopdf/pdftopdf-pdftopdf.o filter/pdftopdf/pdftopdf-pdftopdf_jcl.o filter/pdftopdf/pdftopdf-pdftopdf_processor.o filter/pdftopdf/pdftopdf-qpdf_pdftopdf_processor.o filter/pdftopdf/pdftopdf-pptypes.o filter/pdftopdf/pdftopdf-nup.o filter/pdftopdf/pdftopdf-intervalset.o filter/pdftopdf/pdftopdf-qpdf_tools.o filter/pdftopdf/pdftopdf-qpdf_xobject.o filter/pdftopdf/pdftopdf-qpdf_pdftopdf.o filter/pdftopdf/pdftopdf-qpdf_cm.o -lqpdf -lcups -lldap -ltiff -ljpeg -ldl
