#!/bin/sh
read var
[ "$var" ] || exit 0 # ignore empty output from send-to-printer
DBUS_SESSION_BUS_ADDRESS='unix:path=/run/user/1000/bus' notify-send 'Printer error' "$var"
exit
/etc/cups/cups-files.conf:
-#User lp
-#Group lp
+User user
+Group user
