#!/bin/bash
[ -e $1 ] || { echo No such file; exit 1; }
iconv -f UTF-8 -t UCS-2 $1 >/dev/null 2>&1 || { echo Bad input; exit 1; }
grep -q $'\r' $1 && { printf 'RUN:\nsed -i \x27s/\\r$//\x27 %s\n' $1; exit 1; }
grep -q $'\xC2\xA0' $1 && { printf 'RUN:\nsed -i \x27s/\\xC2\\xA0//g\x27 %s\n' $1; exit 1; }
grep -q $'\xCC\x81' $1 && { printf 'RUN:\nsed -i \x27s/\\xCC\\x81//g\x27 %s\n' $1; exit 1; }
cat ~/prt/reading.tex
cat $1 | \
sed 's/…/.../g' | \
sed 's/–/--/g' | \
sed 's/—/---/g'
echo '\bye'
