#!/bin/sh
file=`python3 -c "$(printf 'import sys, urllib.parse\nprint(urllib.parse.unquote(sys.argv[1]))')" $3`

[ -r $file ] || { echo 'File is not readable by lp user.' | sudo -u user my-notify; exit 1; }
pdffonts $file | grep -q 'Type 1C' && { echo 'Type 1' | sudo -u user my-notify; exit 1; }
# FIXME: does it matter to use `exit 0' or `exit 1'?

( printf '\e%%-12345X'
  echo @PJL JOB
  if ! echo $5 | grep -q Duplex=None; then
    echo @PJL SET DUPLEX=ON
  fi
  echo @PJL ENTER LANGUAGE=POSTSCRIPT
  cat $file
  printf '\e%%-12345X'
  echo @PJL EOJ
  printf '\e%%-12345X'
) | send-to-printer | sudo -u user my-notify
