#!/bin/sh
[ "$engine" = metapost ] && set -- ${3%.tex}
if [ `basename $0` != texpdf ]; then export TEXFONTMAPS=/usr/local; export T1FONTS=/usr/share/texmf/fonts/type1/public/lm; fi # when dvipdfmx will be fixed, rm TEXFONTMAPS and until then don't use LM-fonts
if [ $# = 1 ]; then
  if [ -e $1.tex ]; then
    file=$1.tex
  elif [ -e /home/user/tex/TeXinputs/$1.tex ]; then
    file=/home/user/tex/TeXinputs/$1.tex
  else
    echo \`$1.tex\' does not exist >&2
    exit 1
  fi
  rm -f $1.toc
  if grep -qP '[^\x00-\x7F]' $file; then
    /home/user/tex/тех $1 || exit
  else
    /home/user/tex/plain $1 || exit
  fi
  if [ -e $1.toc ] && grep -q '^\\endinput' $1.toc; then
    eval `sed -n '$p' $1.toc`
    export lastpagenumber
    export total=`sed -n 's/^Output written on .* (\([0-9]\+\) pages\?, [0-9]\+ bytes\?)\.$/\1/p' $1.log`
    num_pages_in_toc=$((total-lastpagenumber))
    n=$((num_pages_in_toc+contentspagenumber))
    if grep -qP '[^\x00-\x7F]' $file; then
      printf %s%s '\pageno='$n ' \input '$1 | /home/user/tex/тех >/dev/null
    else
      printf %s%s '\pageno='$n ' \input '$1 | /home/user/tex/plain >/dev/null
    fi
  fi
else
  exec /home/user/tex/plain
fi
