#!/bin/sh
out=$(mktemp -p /tmp XXXXXXXXXX.w)
if [ "$1" = --duplex ]; then
  file=$2
  if [ "$3" = "" ]; then
    ch=/dev/null
  else
    ch=$3.ch
  fi
else
  file=$1
  if [ "$2" = "" ]; then
    ch=/dev/null
  else
    ch=$2.ch
  fi
fi
if echo $file | grep -q '\.'; then
  file_base=`echo $file|cut -d. -f1`
else
  file_base=$file
  file=$file.w
fi
test -e $file || { echo '! Cannot open input file' $file; exit 1; }
test -e $ch || { echo '! Cannot open change file' $ch; exit 1; }
ctie -m $out $file $ch >/dev/null || { rm -f $out; exit 1; } # expand @i
convert-tex $out >/dev/null || { rm $out; exit 1; }
if [ "$1" = --duplex ]; then
  /usr/local/bin/cweave -e +c +d +y +z $2 $3 $4 || { rm $out; exit 1; }
else
  /usr/local/bin/cweave -e +c +d +y +z "$@" || { rm $out; exit 1; }
  sed -i /pdfhorigin/d $file_base.tex
fi
if sed 's/sigаction/sigaction/g' $file | grep -qP '[^\x00-\x7F]'; then # cyrillic a
  sed -i '1s/$/-ru/' $file_base.tex
fi
cweave-check-@s.pl $out $file_base.idx # FIXME: what about `@f'?
cweave-check-include.pl $out $file_base.idx || { rm $out; exit 1; }
rm $out
cweave-remove-reserved.pl $file_base.idx
cweave-underline.pl $file_base.idx
perl -i -0777 -ne '@a=split/^\\I/m;for (@a[1..$#a]){if(!/\[/){s/^\\\\([^,]+)/\\underbar{\\\\$1}/}print"\\I$_"}' $file_base.idx # identifiers which are not defined are underlined
sed -i 's/sigаction/sigaction/g' $file_base.tex # cyrillic a

#if "internal" identifier is not underlined, it is a sign that it occurs somewhere in your program - then rename it in program
#if identifier is underlined but not "internal", add it after #include
